name: "Auto Check Build iStoreOS Installer ISO"

on:
  schedule:
    - cron: '0 3 * * *'  # 每天凌晨3点检查一次（按需调整） UTC 时间 对应北京时间 11点
  workflow_dispatch:  # 允许手动触发

 jobs:
  jobs_tag:
    runs-on: ubuntu-22.04       # 使用ubuntu-22.04虚拟机执行任务
    steps:
      - name: Get tag version
        uses: actions/checkout@v4
        id: get_tag
        run: |
          URL=https://fw.koolcenter.com/iStoreOS/x86_64_efi/version.index
          LATEST_TAG=curl -s $URL | head -n 1 |cut -d '-' -f2
          LATEST_TIME=curl -s $URL | head -n 1 |cut -d '-' -f1
  
  check:
    runs-on: ubuntu-22.04       # 使用ubuntu-22.04虚拟机执行任务
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch webpage
        run: |
          curl -s https://fw20.koolcenter.com/iStoreOS/x86_64_efi/version.latest -o current.html  # 替换你的URL

      - name: Compare changes
        id: diff
        run: |
          # 确保首次运行时创建基准文件，检查文件是否变化
          if [ ! -f previous.html ]; then
            echo "first_run=true" >> $GITHUB_OUTPUT
            cp current.html previous.html
          elif ! cmp -s current.html previous.html; then
            echo "changed=true" >> $GITHUB_OUTPUT
            mv current.html previous.html
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Run action if changed
        if: steps.diff.outputs.changed == 'true' || steps.diff.outputs.first_run == 'true'
        run: |
          echo "检测到网页变化！执行任务..."
          # 在此添加你的自定义脚本
          # 示例：发送通知 ./send-alert.sh
      - name: "Checking out git repository"
        uses: actions/checkout@v2
        
      - name: Set executable permissions
        run: |
            chmod +x ${{ github.workspace }}/istoreos.sh
            chmod +x ${{ github.workspace }}/supportFiles/istoreos/build.sh
  
      - name: "Build iStoreOS Installer ISO"
        run: |
            ./istoreos.sh
        
      - name: "Publish"
        uses: softprops/action-gh-release@v2.2.1
        with:
          tag_name: "iStoreOS-$LATEST_TIME-$LATEST_TAG-Installer-x86_64-ISO"
          body_path: ${{ github.workspace }}/supportFiles/istoreos/info.md
          files: |
            output/istoreos-installer-x86_64.iso
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}          


      - name: Persist previous version
        if: always()
        run: |
          # 确保文件存在再提交
          if [ -f previous.html ]; then
            git config user.name "github-actions"
            git config user.email "actions@github.com"
            git add previous.html
            git commit -m "Update webpage snapshot [skip ci]" || echo "No changes to commit"
            git push
          else
            echo "previous.html not found, skipping commit"
          fi

